create database vixel;
use vixel;

create table linked (
	discord_id BIGINT PRIMARY KEY,
    uuid varchar(36)
);

CREATE TABLE sessions (
    uuid VARCHAR(36) PRIMARY KEY,
    experience BIGINT,
    created_at TIMESTAMP,
    wins_bedwars BIGINT,
    losses_bedwars BIGINT,
    final_kills_bedwars BIGINT,
    final_deaths_bedwars BIGINT,
    kills_bedwars BIGINT,
    deaths_bedwars BIGINT,
    beds_broken_bedwars BIGINT,
    beds_lost_bedwars BIGINT,
    eight_one_wins_bedwars BIGINT,
    eight_one_losses_bedwars BIGINT,
    eight_one_final_kills_bedwars BIGINT,
    eight_one_final_deaths_bedwars BIGINT,
    eight_one_kills_bedwars BIGINT,
    eight_one_deaths_bedwars BIGINT,
    eight_one_beds_broken_bedwars BIGINT,
    eight_one_beds_lost_bedwars BIGINT,
    eight_two_wins_bedwars BIGINT,
    eight_two_losses_bedwars BIGINT,
    eight_two_final_kills_bedwars BIGINT,
    eight_two_final_deaths_bedwars BIGINT,
    eight_two_kills_bedwars BIGINT,
    eight_two_deaths_bedwars BIGINT,
    eight_two_beds_broken_bedwars BIGINT,
    eight_two_beds_lost_bedwars BIGINT,
    four_three_wins_bedwars BIGINT,
    four_three_losses_bedwars BIGINT,
    four_three_final_kills_bedwars BIGINT,
    four_three_final_deaths_bedwars BIGINT,
    four_three_kills_bedwars BIGINT,
    four_three_deaths_bedwars BIGINT,
    four_three_beds_broken_bedwars BIGINT,
    four_three_beds_lost_bedwars BIGINT,
    four_four_wins_bedwars BIGINT,
    four_four_losses_bedwars BIGINT,
    four_four_final_kills_bedwars BIGINT,
    four_four_final_deaths_bedwars BIGINT,
    four_four_kills_bedwars BIGINT,
    four_four_deaths_bedwars BIGINT,
    four_four_beds_broken_bedwars BIGINT,
    four_four_beds_lost_bedwars BIGINT,
    two_four_wins_bedwars BIGINT,
    two_four_losses_bedwars BIGINT,
    two_four_final_kills_bedwars BIGINT,
    two_four_final_deaths_bedwars BIGINT,
    two_four_kills_bedwars BIGINT,
    two_four_deaths_bedwars BIGINT,
    two_four_beds_broken_bedwars BIGINT,
    two_four_beds_lost_bedwars BIGINT
);
